blog/api/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^user$', views.UserListAPIView.as_view(), name='user-list'),
    url(r'^user/create$', views.UserCreateAPIView.as_view(), name='user-create'),


    # POST GROUP API
    url(r'^groups$', views.GroupListAPIView.as_view(), name='group-list'),
    url(r'^groups/(?P<id>\d+)$', views.GroupDetailAPIView.as_view(), name='group-detail'),

    # #id in bellow url, must defined in PostDetailAPIView as lookup_field field
    # url(r'^(?P<id>\d+)$', views.PostDetailAPIView.as_view(), name='detail'),
    
    # url(r'^(?P<id>\d+)/delete$', views.PostDeleteAPIView.as_view(), name='delete'),
    # url(r'^(?P<id>\d+)/update$', views.PostUpdateAPIView.as_view(), name='update'),

    # url(r'^create/$', views.PostCreateAPIView.as_view(), name='create'),



    # POST API
    url(r'^posts$', views.PostListAPIView.as_view(), name='post-list'),

    #id in bellow url, must defined in PostDetailAPIView as lookup_field field
    url(r'^posts/(?P<id>\d+)$', views.PostDetailAPIView.as_view(), name='post-detail'),
    
    url(r'^posts/(?P<id>\d+)/delete$', views.PostDeleteAPIView.as_view(), name='post-delete'),
    url(r'^posts/(?P<id>\d+)/update$', views.PostUpdateAPIView.as_view(), name='post-update'),

    url(r'^posts/create/$', views.PostCreateAPIView.as_view(), name='post-create'),

]

blog/urls.py
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^(?P<id>[0-9]{1,3})$', views.detail, name='detail'),
    url(r'^create/$', views.create, name='create'),
    url(r'^edit/(?P<id>[0-9]{1,3})$', views.edit, name='edit'),
    url(r'^delete/(?P<id>[0-9]{1,3})$', views.delete, name='delete'),
]

intro_to_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace='blog')),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    # api urls 
    url(r'^api/', include('blog.api.urls', namespace='blog-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.conf import settings

from ckeditor_uploader.fields import RichTextUploadingField


class BlogGroup(models.Model):
    title = models.CharField(_('group title'), max_length=200, default='')

    # python 2.x
    def __unicode__(self):
        return self.title

    # python 3.x
    def __unicode__(self):
        return self.title

class Blog(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('owner'), null=True)
    group = models.ForeignKey(BlogGroup, verbose_name=('group'), related_name='group', on_delete=models.CASCADE, null=True)
    title = models.CharField(_('title'), max_length=120)
    image = models.ImageField(_('main image'), upload_to='blog/%Y-%m-%d', blank=True, null=True)
    content = RichTextUploadingField(_('content'), config_name='default')
    attach_file = models.FileField(_('Attach File'), null=True, blank=True, help_text=_('this is optional.'))
    updateDateTime = models.DateTimeField(_('create date'), auto_now_add=True, auto_now=False)
    createDateTime = models.DateTimeField(_('update date'), auto_now_add=False, auto_now=True)

    # python 2.x
    def __unicode__(self):
        return self.title

    # python 3.x
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'id':self.id})

blog/forms.py
from django import forms
import models
from ckeditor.widgets import CKEditorWidget

class BlogForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget()),

    class Meta:
        model = models.Blog
        fields = ('title', 'image', 'content', 'attach_file')
        

blog/api/views.py
from rest_framework import generics

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import (
    SearchFilter, 
    OrderingFilter,
    )

from rest_framework.permissions import IsAdminUser, AllowAny

from blog.models import Blog, BlogGroup
from .permissions import OwnerCanManageOrReadOnly
from .pagination import (
    PostPageNumberPagination,
    PostLimitOffsetPagination
    )
from .serializers import (
    GroupListSerializer,
    GroupDetailSerializer,

    PostListSerializer,
    PostDetailSerializer,
    PostCreateSerializer,
    PostDeleteSerializer,
    )

from django.db.models import Q
from django.core.exceptions import PermissionDenied


########### POST SERIALIZER ###########
class PostListAPIView(generics.ListAPIView):
    '''
    write api documentation here in markdown syntax
    '''

    # we comment queryset because we defined get_queryset() function in this class
    # queryset = Blog.objects.all()
    
    serializer_class = PostListSerializer
    pagination_class = PostLimitOffsetPagination
    filter_backends = (
        DjangoFilterBackend, # work with filter_fields, Note that this backend imported from django_filters
        SearchFilter, # work with search_filds
        OrderingFilter # work with ordering_fields
        )
    filter_fields = (
        'title', 
        'content', 
        'createDateTime',
        'updateDateTime',
        'owner__username', 
        'owner__first_name', 
        'owner__last_name'
        )
    search_fields = (
        'title', 
        'content', 
        'owner',
        'owner__username', 
        'owner__first_name', 
        'owner__last_name'
        )
    ordering_fields = (
        'id', 
        'title', 
        'content', 
        'owner',
        'owner__username', 
        'owner__first_name', 
        'owner__last_name'
        )


    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            # superuser can see all posts
            queryset = Blog.objects.all()
        else:
            # otherwise every user can see his posts
            queryset = Blog.objects.filter(owner=self.request.user)

        # Custom search. It is not related to rest_framework
        query = self.request.GET.get('q')
        if query:
            # if user search for something by 'q' keyword
            queryset = queryset.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(owner__first_name__icontains=query)|
                Q(owner__last_name__icontains=query)|
                Q(owner__username__icontains=query)
                ).distinct().order_by('-updateDateTime')
        return queryset



class PostDetailAPIView(generics.RetrieveAPIView):
    '''
    write api documentation here in markdown syntax
    '''

    queryset = Blog.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'id'

class PostCreateAPIView(generics.CreateAPIView):
    '''
    write api documentation here in markdown syntax
    '''

    queryset = Blog.objects.all()
    serializer_class = PostCreateSerializer
    permission_classes = (IsAdminUser,)

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
        # you can send email here and etc. this email send when serializer create


class PostDeleteAPIView(generics.RetrieveDestroyAPIView):
    '''
    write api documentation here in markdown syntax
    '''

    queryset = Blog.objects.all()
    serializer_class = PostDeleteSerializer
    permission_classes = (OwnerCanManageOrReadOnly,)
    lookup_field = 'id'

    def perform_destroy(self, serializer):
        # just owner can delete post
        if serializer.owner != self.request.user:
            raise PermissionDenied
        else:
            serializer.delete()
            # you can send email here and etc. this email send when serializer delete


class PostUpdateAPIView(generics.RetrieveUpdateAPIView):
    '''
    write api documentation here in markdown syntax
    '''

    queryset = Blog.objects.all()
    serializer_class = PostDeleteSerializer
    permission_classes = (OwnerCanManageOrReadOnly,)
    lookup_field = 'id'

    def perform_update(self, serializer):
        serializer.save(owner=self.request.user)
        # you can send email here and etc. this email send when serializer update


########### GROUP SERIALIZER ###########\
class GroupListAPIView(generics.ListAPIView):
    queryset = BlogGroup.objects.all()
    serializer_class = GroupListSerializer


class GroupDetailAPIView(generics.RetrieveAPIView):
    queryset = BlogGroup.objects.all()
    serializer_class = GroupDetailSerializer
    lookup_field = 'id'


########## USER SERIALIZER #########
from django.contrib.auth import get_user_model
User = get_user_model()
from serializers import (
    UserListSerializer,
    UserCreateSerializer,
    )

class UserListAPIView(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserListSerializer


class UserCreateAPIView(generics.CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import PermissionDenied
from django.core.paginator import (
    Paginator, 
    EmptyPage, 
    PageNotAnInteger
    )
from forms import BlogForm
from models import Blog


def list(request):

    posts = Blog.objects.all().order_by('-updateDateTime')

    query = request.GET.get('q')
    if query:
        posts = posts.filter(
                    Q(title__icontains=query)|
                    Q(content__icontains=query)
                )


    paginator = Paginator(posts, 5) # Show 5 posts per page

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts
    }
    return render(request, 'list.html', context)


def detail(request, id):
    post = get_object_or_404(Blog, id=id)

    context = {
        'post': post
    }
    return render(request, 'detail.html', context)


def create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = BlogForm(request.POST or None, request.FILES,)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.owner = request.user
        instance.save()
        messages.success(request, _('created successfully! <a href="/">See the item</a>'), extra_tags='alert alert-success safe')
    context = {
        'form': form,
    }
    return render(request, 'create.html', context)


def edit(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Blog, id=id)
    
    # check just owner and superuser can edit current post
    if not request.user.is_superuser and request.user != instance.owner:
        raise PermissionDenied
    
    form = BlogForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.owner = request.user
        form.save()
        messages.success(request, _('updated successfully!!'), extra_tags='alert alert-success')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'form': form,
    }
    return render(request, 'edit.html', context)


def delete(request, id):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    post = get_object_or_404(Blog, id=id)
    if post.delete():
        messages.success(request, _('item deleted successfully!'), extra_tags='alert alert-success')
    return render(request, 'detail.html', {'post': post})

blog/templates/blog_base.html
{% load static i18n %}

<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            {% trans "Blog" %}
        {% endblock title %}
    </title>

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<style type="text/css">
    @font-face {
        font-family: vazir;
        src: {% static "fonts/vazir/vazir.woff" %};
    }

    body {
        font-family: vazir;
        direction: rtl
    }
</style>

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>

</head>
<body>

<nav class="navbar navbar-default">
    <div class="navbar-header pull-right">
        <a class="navbar-brand" href="/">{% trans "BLOG" %}</a>
    </div>
    <ul class="nav navbar-nav pull-right">
        <li><a href="{% url 'blog:list' %}">{% trans "posts" %}</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'blog:create' %}">{% trans "create post" %}</a></li>            
        {% endif %}
    </ul>
    
    

    {% if request.user.is_superuser %}        
        <a class="btn btn-success pull-left" style="margin-top: 7px; margin-left: 10px;" href="/admin">{% trans "dashboard" %}</a>
    {% else %}
        <a class="btn btn-success pull-left" style="margin-top: 7px; margin-left: 10px;" href="/admin">
        <i class="fa fa-sign-in"></i>
        {% trans "login" %}</a>
    {% endif %}


    {% if user.is_authenticated %}
        <a class="btn btn-warning pull-left" style="margin-top: 7px; margin-left: 10px;" href="/admin/logout">{% trans "log out" %}</a>
    {% endif %}


    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-info pull-left" style="margin-top: 7px; margin-left: 10px;" data-toggle="modal" data-target="#myModal">
        <i class="fa fa-search"></i>
        {% trans "search" %}
    </button>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">{% trans "Blog Search" %}</h4>
          </div>
          <div class="modal-body">
            <form class="form-inline" method="GET" action="">
                <input type="text" class="form-control" name="q" size="50" placeholder="جستجو" required="">
                <button type="submit" class="btn btn-danger">{% trans "search" %}</button>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
          </div>
        </div>

      </div>
    </div>

</nav>


<div class="container">
{% block messages %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {% if 'safe' in message.tags%}
                {{ message|safe }}
            {% else %}
                {{ message }}
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock messages %}
</div>


{% if search_result %}
    <div class="container">
        <div class="panel-group">
            {% for result in search_result %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4><a href="{% url 'blog:detail' id=result.id %}">{{ result.title }}</a></h4>
                    </div>
                    <div class="panel-body">{{ result.content|safe|truncatewords_html:50 }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    {% block content %}
        <div class="text-center">
            <h1>{% trans "BLOG SITE" %}</h1>
        </div>
    {% endblock content %}
{% endif %}
</body>
</html>

blog/templates/create.html
{% extends "blog_base.html" %}

{% load staticfiles %}

{% block title %}
    create | {{ block.super }}
{% endblock title %}

{% block content %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<br>
<div class="col-mg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
        <form class="form-group" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.0 }}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" name="submit"/>
        </form>
</div>
{% endblock content %}

blog/templates/delete.html
{% extends "blog_base.html" %}
{% block title %}
    {{ title }} | {{ block.super }}
{% endblock title %}

{% block content %}
    <h1>
        delete page
    </h1>
{% endblock content %}

blog/templates/detail.html
{% extends "blog_base.html" %}
{% load i18n %}
{% block content %}
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3">
    {% if  post.image %}
        <div class="row">
            <div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
                <a href="{% url 'blog:detail' id=post.id %}">
                    <img class="img-responsive img-rounded" src="{{ post.image.url }}" style="max-height: 350px; margin: 0 auto;">
                </a>
            </div>
        </div>
    {% endif %}
    <div class="text-center">
        <a href="{% url 'blog:detail' id=post.id %}">
            <h2>{{ post.title }}</h2>
        </a>
    </div>
    <p>{{ post.content|safe }}</p>
    <hr>
    {% if post.attach_file %}    
        <a href="{{ post.attach_file.url }}"> دانلود فایل ضمیمه </a>
        <br>
    {% endif %}
    <small>{{ post.updateDateTime }}</small>
    <br>
    <br>
    <br>
    <br>
</div>
{% endblock content %}

blog/templates/edit.html
{% extends "blog_base.html" %}
{% load i18n staticfiles %}

{% block content %}
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">{% trans "save" %}</button>
    </form>
</div>
{% endblock content %}

blog/templates/list.html
{% extends "blog_base.html" %}
{% load i18n %}
{% block content %}
    {{ block.super }}
<div class="container">
    {% for post in posts %}
        <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-body">
                {% if  post.image %}
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-lg-offset-3 col-md-offset-3">
                            <a href="{% url 'blog:detail' id=post.id %}">
                                <img class="img-responsive img-rounded" src="{{ post.image.url }}" style="max-height: 350px; margin: 0 auto;">
                            </a>
                        </div>
                    </div>
                {% endif %}
                <h2>
                    <a href="{% url 'blog:detail' id=post.id %}">
                        {{ post.title }}
                    </a>
                    <br>
                    <small>{{ post.updateDateTime|timesince }} {% trans "ago" %}</small>
                </h2>
                <p>{{ post.content|safe|truncatewords_html:50 }}</p>
                <a href="{% url 'blog:detail' id=post.id %}" class="btn btn-default">{% trans "view" %}</a>
                <br>
                <small>
                {% if user.is_authenticated %}
                    <a class="btn btn-danger btn-xs" href="{% url 'blog:delete' id=post.id %}">{% trans "delete" %}</a>
                    <a class="btn btn-primary btn-xs" href="{% url 'blog:edit' id=post.id %}">{% trans "edit" %}</a>
                {% endif %}
                </small>
              </div>
            </div>
        </div>
    {% endfor %}

<div class="row">
    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                {% trans "Page" %} {{ posts.number }} {% trans "of" %} {{ posts.paginator.num_pages }}.
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
</div>

</div>
{% endblock content %}